apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso-demo
    spec:
      volumes:
        - name: tmp-path
          emptyDir: {}
      containers:
      - image: ennc0d3/dsodemo
        name: dsodemo
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "150m"
            memory: "250Mi"
        securityContext:
          readOnlyRootFilesystem: true
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - name: tmp-path
            mountPath: /tmp/


